// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

#ifndef PROTOBUF_index_2eproto__INCLUDED
#define PROTOBUF_index_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_index_2eproto();
void protobuf_AssignDesc_index_2eproto();
void protobuf_ShutdownFile_index_2eproto();

class object;
class object_array;
class object_item;

// ===================================================================

class object_array : public ::google::protobuf::MessageLite {
 public:
  object_array();
  virtual ~object_array();

  object_array(const object_array& from);

  inline object_array& operator=(const object_array& from) {
    CopyFrom(from);
    return *this;
  }

  static const object_array& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const object_array* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(object_array* other);

  // implements Message ----------------------------------------------

  object_array* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const object_array& from);
  void MergeFrom(const object_array& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 val = 1 [packed = true];
  inline int val_size() const;
  inline void clear_val();
  static const int kValFieldNumber = 1;
  inline ::google::protobuf::int64 val(int index) const;
  inline void set_val(int index, ::google::protobuf::int64 value);
  inline void add_val(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      val() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_val();

  // @@protoc_insertion_point(class_scope:object.array)
 private:

  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > val_;
  mutable int _val_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_index_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_index_2eproto();
  #endif
  friend void protobuf_AssignDesc_index_2eproto();
  friend void protobuf_ShutdownFile_index_2eproto();

  void InitAsDefaultInstance();
  static object_array* default_instance_;
};
// -------------------------------------------------------------------

class object_item : public ::google::protobuf::MessageLite {
 public:
  object_item();
  virtual ~object_item();

  object_item(const object_item& from);

  inline object_item& operator=(const object_item& from) {
    CopyFrom(from);
    return *this;
  }

  static const object_item& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const object_item* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(object_item* other);

  // implements Message ----------------------------------------------

  object_item* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const object_item& from);
  void MergeFrom(const object_item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .object.array arrays = 1;
  inline int arrays_size() const;
  inline void clear_arrays();
  static const int kArraysFieldNumber = 1;
  inline const ::object_array& arrays(int index) const;
  inline ::object_array* mutable_arrays(int index);
  inline ::object_array* add_arrays();
  inline const ::google::protobuf::RepeatedPtrField< ::object_array >&
      arrays() const;
  inline ::google::protobuf::RepeatedPtrField< ::object_array >*
      mutable_arrays();

  // required int64 key = 2;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 2;
  inline ::google::protobuf::int64 key() const;
  inline void set_key(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:object.item)
 private:
  inline void set_has_key();
  inline void clear_has_key();

  ::google::protobuf::RepeatedPtrField< ::object_array > arrays_;
  ::google::protobuf::int64 key_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_index_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_index_2eproto();
  #endif
  friend void protobuf_AssignDesc_index_2eproto();
  friend void protobuf_ShutdownFile_index_2eproto();

  void InitAsDefaultInstance();
  static object_item* default_instance_;
};
// -------------------------------------------------------------------

class object : public ::google::protobuf::MessageLite {
 public:
  object();
  virtual ~object();

  object(const object& from);

  inline object& operator=(const object& from) {
    CopyFrom(from);
    return *this;
  }

  static const object& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const object* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(object* other);

  // implements Message ----------------------------------------------

  object* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const object& from);
  void MergeFrom(const object& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef object_array array;
  typedef object_item item;

  // accessors -------------------------------------------------------

  // repeated .object.item items = 1;
  inline int items_size() const;
  inline void clear_items();
  static const int kItemsFieldNumber = 1;
  inline const ::object_item& items(int index) const;
  inline ::object_item* mutable_items(int index);
  inline ::object_item* add_items();
  inline const ::google::protobuf::RepeatedPtrField< ::object_item >&
      items() const;
  inline ::google::protobuf::RepeatedPtrField< ::object_item >*
      mutable_items();

  // @@protoc_insertion_point(class_scope:object)
 private:

  ::google::protobuf::RepeatedPtrField< ::object_item > items_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_index_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_index_2eproto();
  #endif
  friend void protobuf_AssignDesc_index_2eproto();
  friend void protobuf_ShutdownFile_index_2eproto();

  void InitAsDefaultInstance();
  static object* default_instance_;
};
// ===================================================================


// ===================================================================

// object_array

// repeated int64 val = 1 [packed = true];
inline int object_array::val_size() const {
  return val_.size();
}
inline void object_array::clear_val() {
  val_.Clear();
}
inline ::google::protobuf::int64 object_array::val(int index) const {
  return val_.Get(index);
}
inline void object_array::set_val(int index, ::google::protobuf::int64 value) {
  val_.Set(index, value);
}
inline void object_array::add_val(::google::protobuf::int64 value) {
  val_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
object_array::val() const {
  return val_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
object_array::mutable_val() {
  return &val_;
}

// -------------------------------------------------------------------

// object_item

// repeated .object.array arrays = 1;
inline int object_item::arrays_size() const {
  return arrays_.size();
}
inline void object_item::clear_arrays() {
  arrays_.Clear();
}
inline const ::object_array& object_item::arrays(int index) const {
  return arrays_.Get(index);
}
inline ::object_array* object_item::mutable_arrays(int index) {
  return arrays_.Mutable(index);
}
inline ::object_array* object_item::add_arrays() {
  return arrays_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::object_array >&
object_item::arrays() const {
  return arrays_;
}
inline ::google::protobuf::RepeatedPtrField< ::object_array >*
object_item::mutable_arrays() {
  return &arrays_;
}

// required int64 key = 2;
inline bool object_item::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void object_item::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void object_item::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void object_item::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
  clear_has_key();
}
inline ::google::protobuf::int64 object_item::key() const {
  return key_;
}
inline void object_item::set_key(::google::protobuf::int64 value) {
  set_has_key();
  key_ = value;
}

// -------------------------------------------------------------------

// object

// repeated .object.item items = 1;
inline int object::items_size() const {
  return items_.size();
}
inline void object::clear_items() {
  items_.Clear();
}
inline const ::object_item& object::items(int index) const {
  return items_.Get(index);
}
inline ::object_item* object::mutable_items(int index) {
  return items_.Mutable(index);
}
inline ::object_item* object::add_items() {
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::object_item >&
object::items() const {
  return items_;
}
inline ::google::protobuf::RepeatedPtrField< ::object_item >*
object::mutable_items() {
  return &items_;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_index_2eproto__INCLUDED
